apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: microservices-workshop
data:
  prometheus-config.yml: |
    scrape_configs:
    - job_name: "spring-boot-actuator"
      metrics_path: "/actuator/prometheus"
      kubernetes_sd_configs:
        - role: pod
          namespaces:
            own_namespace: true
      relabel_configs:
      # Example relabel to scrape only pods that have
      # "prometheus.io/should_be_scraped = true" annotation.
        - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_should_be_scraped]
          action: keep
          regex: true
      # Example relabel to scrape only single, desired port for the pod
      # based on pod "prometheus.io/scrape_port = <port>" annotation.
        - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_scrape_port]
          action: replace
          regex: ([^:]+)(?::\d+)?;(\d+)
          replacement: $1:$2
          target_label: __address__
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - source_labels: [__meta_kubernetes_namespace]
          action: replace
          target_label: namespace
        - source_labels: [__meta_kubernetes_pod_name]
          action: replace
          target_label: pod
