apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-init
  namespace: microservices-workshop
data:
  mongo-init.js: |
    db.customers.insertOne({
        _id: "a13dfdb8-6e30-4d31-99e4-62c3a308e310",
        deliveryAddress: {
            name: "Jan Kowalski",
            address: "ul. Nowowiejska 15, 10-100 Nowe Miasto"
        }
    })
