apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: microservices-workshop
spec:
  selector:
    app: kafka-broker
  ports:
    - protocol: TCP
      port: 29092
      targetPort: 29092
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: microservices-workshop
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181
      targetPort: 2181
---
apiVersion: v1
kind: Service
metadata:
  name: schemaregistry
  namespace: microservices-workshop
spec:
  selector:
    app: schemaregistry
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-ui
  namespace: microservices-workshop
spec:
  selector:
    app: kafka-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
